name: Oneblock
description: Sterling Bank OneBlock

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 12.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  masked_controller: ^1.0.1
  flutter_masked_text:
#  google_maps_flutter: ^0.5.21+15
  dio: ^3.0.9
#  screen: ^0.0.5
#  flutter_ringtone_player: ^1.0.0
  cupertino_icons: ^0.1.3
#  page_view_indicator: ^0.3.0
  image_picker: ^0.6.3+1
  image_cropper: ^1.2.1
#  flutter_places_dialog: ^1.0.2
#  google_places_picker: ^2.0.2+2
  connectivity: ^0.4.6+1
  pull_to_refresh: 1.5.6
  device_id: ^0.2.0
  cached_network_image: ^2.0.0
#  flutter_html: ^0.11.1
#  photo: ^0.2.0
  timeago: ^2.0.22
  photo_manager: 0.3.4
  permission_handler: ^4.0.0
  package_info: ^0.4.0+13
  ntp: ^1.0.4
  country_pickers: ^1.1.0
  # thumbnails: ^1.0.1
  photo_view: 0.9.0
#  clipboard_manager: ^0.0.4
#  flutter_staggered_grid_view: ^0.3.0
#  flutter_document_picker: 3.0.1
#  file_picker: 1.9.0+1
  flutter_spinkit: ^4.1.1+1
#  flutter_simple_video_player: 0.0.9
  uuid: 2.0.0
  path: any
#  flutter_money_formatter: ^0.8.3


#  flutter_ravepay: ^0.2.0
#  flutter_sound: ^2.0.3
#  keyboard_visibility: ^0.5.6
#  emoji_picker: ^0.0.2
  filesize: ^1.0.4
#  progress_hud: ^1.1.0
#  cloud_firestore: ^0.13.0+1
#  firebase_storage: ^3.1.0
#  firebase_auth: ^0.15.2
#  firebase_messaging: ^6.0.9
#  firebase_analytics: ^5.0.9
#  flutter_linkify: ^2.1.0
#  audio_recorder2: ^1.0.3
#  audioplayer: ^0.5.2
#  vibration: ^1.2.2
#  dashed_circle: ^0.0.1
  datetime_picker_formfield: ^0.4.3
  shared_preferences: ^0.5.6

#  flutter_rave: ^0.0.5
  flutter_local_notifications: ^0.9.1
  rxdart: ^0.23.1
#  rave_flutter: ^0.0.8-alpha+1


  dio_flutter_transformer: ^3.0.2
#  equatable: ^1.0.1
#  flushbar: ^1.9.1
  intl: ^0.16.0
#  crypto: ^2.1.4
#  tripledes: ^2.1.0
#  flutter_webview_plugin: ^0.3.10
  url_launcher: 5.4.11
#  url_launcher_web: 0.1.2
#  webview_flutter: ^0.3.18+1
#  android_alarm_manager: ^0.4.5+2
#  animated_text_kit: ^1.3.1
#  place_picker: ^0.9.11
#  flutter_google_ad_manager: ^0.10.1
#  cloud_functions: ^0.4.1+6
#  money_field: ^1.0.1
#  csv: ^4.0.3
#  latlong: ^0.6.1
  synchronized: ^2.2.0
#  liquid_swipe: ^1.3.1
#  flutter_rating_bar: ^3.0.1+1
  http: ^0.12.0+4
  json_annotation: ^3.0.1
#  flutter_lock_screen: ^1.0.6
  local_auth: ^0.6.0
#  pdf: ^1.6.0
#  excel: 1.0.2
  open_file: ^3.0.1

#  flutter_cache_manager: 1.1.3

  pin_code_fields: ^3.1.2
  pin_entry_text_field: ^0.1.4

#  qr_code_scanner: ^0.0.13
#  flutter_qr_bar_scanner: ^1.0.2
  flutter_plugin_qr_scanner: ^0.0.1
  qr_flutter: ^3.2.0
  share: ^0.6.4+3








dependency_overrides:
  xml: ^4.1.0
  intl: ^0.15.8
  flutter_svg: ^0.18.0
  equatable: ^0.6.1
#  path_provider: ^0.4.1
#  flutter_icons: ^1.0.0+1
#  flutter_cache_manager: 1.0.0

dev_dependencies:
  build_runner: ^1.7.4
  json_serializable: ^3.2.5
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:


  fonts:
       - family: Nirmala
         fonts:
           - asset: assets/fonts/Nirmala.ttf


       - family: NirmalaB
         fonts:
           - asset: assets/fonts/NirmalaB.ttf

       - family: curve
         fonts:
           - asset: assets/fonts/curve.ttf

       - family: curveB
         fonts:
           - asset: assets/fonts/curveB.ttf




  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
    - assets/icons/
    - assets/sounds/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
#   fonts:
#     - family: Schyler
#       fonts:
#         - asset: fonts/Schyler-Regular.ttf
#         - asset: fonts/Schyler-Italic.ttf
#           style: italic
#     - family: Trajan Pro
#       fonts:
#         - asset: fonts/TrajanPro.ttf
#         - asset: fonts/TrajanPro_Bold.ttf
#           weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
